### PR TITLE
Disable ads on the legal notice page

### LINKED ISSUE #10: Set __disableAds=true for legalNotice.tpl

### PR DESCRIPTION
**Pull request by SoftCreatR**
Resolves #10

### CODE REVIEW

**Comment by TimWolla** [comment]
This is incomplete (doesn't take the footer into account) and really should have referenced issue #10 with a “Resolves #xx” remark in the commit message.

**Comment by TimWolla** [comment]
On an unrelated note:

> First-time contributors need a maintainer to approve running workflows. Learn more. 

I really thought this would only apply to PRs that modify anything within `.github/`, but I guess it must reject all of them in case the workflow just invokes a script.

**Comment by SoftCreatR** [comment]
> This is incomplete (doesn't take the footer into account) and really should have referenced issue #10 with a “Resolves #xx” remark in the commit message.

Didn't see the Issue you created, sorry about that.

**Comment by TimWolla** [comment]
Do I really need to re-approve the GitHub workflow?!

**Comment by SoftCreatR** [comment]
> Do I really need to re-approve the GitHub workflow?!

I guess, that only stops after merging changes from first-time contributors.

**Comment by TimWolla** [comment]
Yeah, looks like that. In fact I had to press the button twice, because the `pull_request.yml` workflow was re-scheduled after requesting a review …

**Comment by SoftCreatR** [comment]
> Yeah, looks like that. In fact I had to press the button twice, because the `pull_request.yml` workflow was re-scheduled after requesting a review …

Because you're currently watching for all activities of the `pull_request` event. See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

**Comment by TimWolla** [comment]
> Because you're currently watching for all activities of the `pull_request` event.

Yeah, I know. This list is somewhat intentional. But I expected GitHub to simply trust the repeated execution if the top-most commit of the PR does not change :pensive:

**Review by BurntimeX — APPROVED** [review]

**Pull request merged**
